### ISSUE TITLE
Suggestion d'amélioration pour Ameli

### ISSUE THREAD

**Issue by AntoineTurmel** [AssuranceMaladieSec/ressources-faq-assures#1]
Bonjour, je me permet de faire une suggestion ici, ma demande étant je pense ignorée à la fois sur Twitter et via le champs Contact d'Ameli.

Ma suggestion : Est ce qu'il est possible d'avertir les assurés quand leur médecin traitant pars à la retraite et que son dossier n'est pas repris ? C'est un peu embêtant de se retrouver sans médecin traitant... 

La réponse du champ contact d'Ameli :
![image](https://user-images.githubusercontent.com/119288/135763221-671e8037-737a-4638-b38b-f4129e1a6508.png)

Est ce possible de faire remonter cette suggestion aux décideurs et/ou développeurs ?

Merci par avance :)

**Comment by cbrocas** [comment]
Bonjour,
Vous êtes ici sur un dépôt de ressources utilisées dans le cadre de la diffusion d'[informations Sécurité auprès des assurés sur le forum ameli](https://forum-assures.ameli.fr/questions/2587780-faq-securite-assures-internet) . 
Via la page contact ameli, vous avez reçu une première réponse essayant de répondre sur le fond à votre souci (ne plus avoir de médecin traitant) et vous trouver une solution.
Si vous souhaitez faire remonter votre suggestion de modification du site assure.ameli.fr, vous pouvez tenter de le faire [via le forum ameli](https://forum-assures.ameli.fr/). 
Je clos l'issue qui n'a aucun lien avec ce dépôt.
